/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sections: Section;
    'contenido-blog': ContenidoBlog;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    'contenido-blog': ContenidoBlogSelect<false> | ContenidoBlogSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Contenido de las diferentes secciones del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  titulo: string;
  seccion: 'inicio' | 'sobre-nosotros' | 'servicios' | 'comunidad' | 'ayuda' | 'contacto' | 'footer';
  tipo:
    | 'hero'
    | 'experiencias'
    | 'historia'
    | 'equipo'
    | 'servicio'
    | 'guia'
    | 'testimonio'
    | 'noticia'
    | 'faq'
    | 'tutorial'
    | 'politica'
    | 'contacto'
    | 'formulario';
  contenido: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  subtitulo?: string | null;
  imagen?: (string | null) | Media;
  /**
   * Para botones o enlaces
   */
  enlace?: string | null;
  /**
   * Texto que aparece en el botón/enlace
   */
  textoEnlace?: string | null;
  /**
   * Número que determina el orden en que aparece el contenido
   */
  orden: number;
  /**
   * Marcar para hacer visible en el frontend
   */
  publicado?: boolean | null;
  metadata?: {
    autor?: string | null;
    cargo?: string | null;
    calificacion?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Contenido estructurado de todas las secciones del sitio web
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-blog".
 */
export interface ContenidoBlog {
  id: string;
  seccion: 'inicio' | 'sobre_nosotros' | 'servicios' | 'comunidad' | 'ayuda' | 'contacto';
  inicio?: {
    titulo?: string | null;
    descripcion?: string | null;
    estadisticas?: {
      transacciones?: number | null;
      eventos_realizados?: number | null;
      productores?: number | null;
    };
    noticias?: string | null;
  };
  sobre_nosotros?: {
    titulo?: string | null;
    descripcion?: string | null;
    fundadores?:
      | {
          nombre?: string | null;
          cargo?: string | null;
          id?: string | null;
        }[]
      | null;
    equipo?:
      | {
          nombre?: string | null;
          area?: string | null;
          detalle?: string | null;
          id?: string | null;
        }[]
      | null;
    notas?:
      | {
          nota?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  servicios?: {
    descripcion?: string | null;
    principales?:
      | {
          servicio?: string | null;
          id?: string | null;
        }[]
      | null;
    notas?:
      | {
          nota?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  comunidad?: {
    descripcion?: string | null;
    testimonios?:
      | {
          texto?: string | null;
          autor?: string | null;
          id?: string | null;
        }[]
      | null;
    notas?:
      | {
          nota?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ayuda?: {
    descripcion_general?: string | null;
    como_comprar?: {
      introduccion?: string | null;
      video?: string | null;
      pasos?:
        | {
            titulo?: string | null;
            detalle?: string | null;
            pagos_presenciales?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    recepcion_tickets?: {
      descripcion?: string | null;
      instrucciones?:
        | {
            paso?: string | null;
            id?: string | null;
          }[]
        | null;
      nota?: string | null;
      asistencia?: string | null;
    };
    acceso_evento?: {
      descripcion?: string | null;
    };
    como_vender?: {
      introduccion?: string | null;
      video?: string | null;
      pasos?:
        | {
            titulo?: string | null;
            detalle?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    politicas?: {
      cancelacion_eventos?: string | null;
      reprogramacion?: string | null;
      imposibilidad_asistencia?: string | null;
    };
    ayuda_tecnica?: {
      uso_totem?: {
        descripcion?: string | null;
        video?: string | null;
      };
      cambio_rollo?:
        | {
            paso?: string | null;
            id?: string | null;
          }[]
        | null;
      cancelar_compra_totem?: {
        descripcion?: string | null;
        campos?:
          | {
              campo?: string | null;
              id?: string | null;
            }[]
          | null;
      };
      solicitar_nuevos_rollos?: string | null;
    };
  };
  contacto?: {
    descripcion?: string | null;
    formulario?:
      | {
          campo?: string | null;
          id?: string | null;
        }[]
      | null;
    email?: string | null;
    telefono?: string | null;
    nota?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'contenido-blog';
        value: string | ContenidoBlog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  titulo?: T;
  seccion?: T;
  tipo?: T;
  contenido?: T;
  subtitulo?: T;
  imagen?: T;
  enlace?: T;
  textoEnlace?: T;
  orden?: T;
  publicado?: T;
  metadata?:
    | T
    | {
        autor?: T;
        cargo?: T;
        calificacion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contenido-blog_select".
 */
export interface ContenidoBlogSelect<T extends boolean = true> {
  seccion?: T;
  inicio?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        estadisticas?:
          | T
          | {
              transacciones?: T;
              eventos_realizados?: T;
              productores?: T;
            };
        noticias?: T;
      };
  sobre_nosotros?:
    | T
    | {
        titulo?: T;
        descripcion?: T;
        fundadores?:
          | T
          | {
              nombre?: T;
              cargo?: T;
              id?: T;
            };
        equipo?:
          | T
          | {
              nombre?: T;
              area?: T;
              detalle?: T;
              id?: T;
            };
        notas?:
          | T
          | {
              nota?: T;
              id?: T;
            };
      };
  servicios?:
    | T
    | {
        descripcion?: T;
        principales?:
          | T
          | {
              servicio?: T;
              id?: T;
            };
        notas?:
          | T
          | {
              nota?: T;
              id?: T;
            };
      };
  comunidad?:
    | T
    | {
        descripcion?: T;
        testimonios?:
          | T
          | {
              texto?: T;
              autor?: T;
              id?: T;
            };
        notas?:
          | T
          | {
              nota?: T;
              id?: T;
            };
      };
  ayuda?:
    | T
    | {
        descripcion_general?: T;
        como_comprar?:
          | T
          | {
              introduccion?: T;
              video?: T;
              pasos?:
                | T
                | {
                    titulo?: T;
                    detalle?: T;
                    pagos_presenciales?: T;
                    id?: T;
                  };
            };
        recepcion_tickets?:
          | T
          | {
              descripcion?: T;
              instrucciones?:
                | T
                | {
                    paso?: T;
                    id?: T;
                  };
              nota?: T;
              asistencia?: T;
            };
        acceso_evento?:
          | T
          | {
              descripcion?: T;
            };
        como_vender?:
          | T
          | {
              introduccion?: T;
              video?: T;
              pasos?:
                | T
                | {
                    titulo?: T;
                    detalle?: T;
                    id?: T;
                  };
            };
        politicas?:
          | T
          | {
              cancelacion_eventos?: T;
              reprogramacion?: T;
              imposibilidad_asistencia?: T;
            };
        ayuda_tecnica?:
          | T
          | {
              uso_totem?:
                | T
                | {
                    descripcion?: T;
                    video?: T;
                  };
              cambio_rollo?:
                | T
                | {
                    paso?: T;
                    id?: T;
                  };
              cancelar_compra_totem?:
                | T
                | {
                    descripcion?: T;
                    campos?:
                      | T
                      | {
                          campo?: T;
                          id?: T;
                        };
                  };
              solicitar_nuevos_rollos?: T;
            };
      };
  contacto?:
    | T
    | {
        descripcion?: T;
        formulario?:
          | T
          | {
              campo?: T;
              id?: T;
            };
        email?: T;
        telefono?: T;
        nota?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}