/**
 * SuggestedActions Component
 *
 * Displays suggested messages when chat is empty (messages.length === 0)
 * These are NOT generated by the model - they are predefined UI hints
 */

import React from "react";
import "./SuggestedActions.css";

const SUGGESTED_ACTIONS = [
  {
    icon: "fa-ticket",
    label: "Cómo comprar",
    message: "Cómo compro entradas?",
  },
  {
    icon: "fa-store",
    label: "Cómo vender",
    message: "Cómo vendo entradas para mi evento?",
  },
  {
    icon: "fa-users",
    label: "Sobre nosotros",
    message: "Quiénes son RedTickets?",
  },
  {
    icon: "fa-envelope",
    label: "Contacto",
    message: "Cómo los contacto?",
  },
];

export function SuggestedActions({ onSelectAction }) {
  return (
    <div className="suggested-actions">
      <p className="suggested-actions-title">¿En qué puedo ayudarte?</p>
      <div className="suggested-actions-grid">
        {SUGGESTED_ACTIONS.map((action, index) => (
          <button
            key={index}
            className="suggested-action-button"
            onClick={() => onSelectAction(action.message)}
          >
            <i className={`fas ${action.icon} action-icon`}></i>
            <span className="action-label">{action.label}</span>
          </button>
        ))}
      </div>
    </div>
  );
}
